# Generated by Django 2.1.5 on 2019-02-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('post', models.TextField()),
                ('status', models.CharField(default='yes', max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('photo', models.TextField()),
                ('photo2', models.TextField()),
                ('photo3', models.TextField()),
            ],
        ),
    ]
