# Generated by Django 2.1.5 on 2019-02-07 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190207_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='userName',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
