# Generated by Django 2.1.5 on 2019-02-10 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190207_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='limitations',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='merits',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
