# Generated by Django 2.1.5 on 2019-02-10 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190210_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='category',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
