# Generated by Django 2.1.5 on 2019-02-10 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comments_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
