# Generated by Django 2.1.5 on 2019-02-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='avaible_sizes',
            field=models.TextField(default='x,x,x'),
            preserve_default=False,
        ),
    ]
