# Generated by Django 2.1.5 on 2019-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190224_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo3',
            field=models.TextField(default=None, null=True),
        ),
    ]
