# Generated by Django 2.1.5 on 2019-02-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20190224_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo3',
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
